In [1]:
# import the importance library
#Defining Parameters
import numpy as np 

# define some parameters
q = 127
n = 8
N = int(1.1 * n * np.log(q))

sigma = 1.0

n, N, q

(8, 42, 127)

In [2]:
import numpy as np

# Convert text to binary representation
def text_to_binary(text):
    binary_message = ''.join(format(ord(char), '08b') for char in text)  # Convert each char to 8-bit binary
    return binary_message

# Convert binary string into an array of integers
def binary_to_array(binary_message, n):
    # Convert the binary string to an array of integers
    binary_array = np.array([int(bit) for bit in binary_message], dtype=np.int32)
    
    # Pad with zeros or truncate to fit the size `n+1`
    if len(binary_array) < n+1:
        binary_array = np.concatenate([binary_array, np.zeros(n+1 - len(binary_array), dtype=int)])
    else:
        binary_array = binary_array[:n+1]
    
    return binary_array



In [3]:
def binary_to_text(binary_array):
    # Join the binary array into a single binary string
    binary_string = ''.join(str(bit) for bit in binary_array)
    
    # Split the binary string into 8-bit chunks (since each character is 8 bits)
    text = ''.join(chr(int(binary_string[i:i+8], 2)) for i in range(0, len(binary_string), 8))
    return text

In [4]:
#Private Key
t = np.random.randint(0, high=q/2, size=n)
s = np.concatenate([np.ones(1, dtype=np.int32), t])
s

array([ 1, 22, 16, 42, 27, 14, 51, 21, 26])

In [5]:
#Public Key
A = np.random.randint(0, high=q/2, size=(N, n))
e = np.round(np.random.randn(N) * sigma ** 2).astype(np.int32) % q
b = ((np.dot(A, t) + e).reshape(-1, 1)) % q

P = np.hstack([b, -A])

In [6]:
#Encryption
# Let's random `r`
r = np.random.randint(0, 2, N) 
# create a message `m`
#text_message="M"
"""
binary_message = text_to_binary(text_message)
print(binary_message)
print(binary_to_text(binary_message))
binary_array=[]
for i in range (len(text_message)):
  binary_array.append(binary_to_array(binary_message[i], n))
"""
m = np.concatenate([np.array([1]), np.zeros(n, dtype=np.int32)])
#m=binary_array
m

array([1, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
c = (np.dot(P.T, r) + (np.floor(q / 2) * m)).astype(np.int32) % q
c

array([ 68,  96,  54,   3,  60,  43,  92, 111, 111], dtype=int32)

In [8]:
#Decryption
m_hat = round((np.dot(c, s) % q) * (2 / q)) % 2
m_hat

1

In [9]:
"""

# Decryption: Decrypt bit by bit (loop over the size of the message)
m_hat = np.zeros(n+1, dtype=np.int32)  # Initialize m_hat to hold the decrypted binary message
for i in range(n+1):
    decrypted_bit = round((np.dot(c, s) % q) * (2 / q)) % 2
    m_hat[i] = decrypted_bit

# Convert decrypted binary array back to text
decrypted_message = binary_to_text(m_hat)
print("Original Message:", text_message)
print("Decrypted Message:", decrypted_message)
"""

'\n\n# Decryption: Decrypt bit by bit (loop over the size of the message)\nm_hat = np.zeros(n+1, dtype=np.int32)  # Initialize m_hat to hold the decrypted binary message\nfor i in range(n+1):\n    decrypted_bit = round((np.dot(c, s) % q) * (2 / q)) % 2\n    m_hat[i] = decrypted_bit\n\n# Convert decrypted binary array back to text\ndecrypted_message = binary_to_text(m_hat)\nprint("Original Message:", text_message)\nprint("Decrypted Message:", decrypted_message)\n'